HydroServerTools/Controllers/ExportController.cs
using CsvHelper;
using HydroServerTools.Models;
using HydroserverToolsBusinessObjects;
using HydroserverToolsBusinessObjects.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;


namespace HydroServerTools.Controllers
{
    public class ExportController : Controller
    {
        //
        public string instanceIdentifier = System.Web.HttpContext.Current.User.Identity.Name;

        // GET: /Export/
        public FileStreamResult Download(int identifier, string viewName)
        {
            //add suffix for download depending on tab
            string downloadSuffix = string.Empty;
            switch (identifier)
            {
                case 0:
                    downloadSuffix = "new";
                    break;
                case 1:
                    downloadSuffix = "rejected";
                    break;
                case 2:
                    downloadSuffix = "update";
                    break;
                case 3:
                    downloadSuffix = "duplicate";
                    break;
            }

            var filename = viewName + "_" + downloadSuffix + ".csv";

            if (viewName == "sites")
            {

                var listOfRecords = (List<SiteModel>)BusinessObjectsUtils.GetRecordsFromCache<SiteModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "variables")
            {
                var listOfRecords = (List<VariablesModel>)BusinessObjectsUtils.GetRecordsFromCache<VariablesModel>(instanceIdentifier, identifier);
                var result = WriteCsvToMemory(listOfRecords);

                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "offsettypes")
            {

                var listOfRecords = (List<OffsetTypesModel>)BusinessObjectsUtils.GetRecordsFromCache<OffsetTypesModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "sources")
            {

                var listOfRecords = (List<SourcesModel>)BusinessObjectsUtils.GetRecordsFromCache<SourcesModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "methods")
            {
                var listOfRecords = (List<MethodModel>)BusinessObjectsUtils.GetRecordsFromCache<MethodModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "labmethods")
            {
                var listOfRecords = (List<LabMethodModel>)BusinessObjectsUtils.GetRecordsFromCache<LabMethodModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "samples")
            {
                var listOfRecords = (List<SampleModel>)BusinessObjectsUtils.GetRecordsFromCache<SampleModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "qualifiers")
            {
                var listOfRecords = (List<QualifiersModel>)BusinessObjectsUtils.GetRecordsFromCache<QualifiersModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "qualitycontrollevels")
            {
                var listOfRecords = (List<QualityControlLevelModel>)BusinessObjectsUtils.GetRecordsFromCache<QualityControlLevelModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "datavalues")
            {
                var listOfRecords = (List<DataValuesModel>)BusinessObjectsUtils.GetRecordsFromCache<DataValuesModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "groupdescriptions")
            {
                var listOfRecords = (List<GroupDescriptionModel>)BusinessObjectsUtils.GetRecordsFromCache<GroupDescriptionModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "groups")
            {
                var listOfRecords = (List<GroupsModel>)BusinessObjectsUtils.GetRecordsFromCache<GroupsModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "derivedfrom")
            {
                var listOfRecords = (List<DerivedFromModel>)BusinessObjectsUtils.GetRecordsFromCache<DerivedFromModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }
            if (viewName == "categories")
            {
                var listOfRecords = (List<CategoriesModel>)BusinessObjectsUtils.GetRecordsFromCache<CategoriesModel>(instanceIdentifier, identifier);

                var result = WriteCsvToMemory(listOfRecords);
                var memoryStream = new MemoryStream(result);
                return new FileStreamResult(memoryStream, "text/csv") { FileDownloadName = filename };
            }

            return null;
        }

        public ActionResult DownloadTemplate(string id)
        {
                     
                try
                {
                    //var fs = System.IO.File.Open(Server.MapPath("~/Templates/ODMTemplates_" + id));
                    var dir = "~/Templates/";
                    var filename = "ODMTemplate_" + id + ".csv";
                    var filePath = Server.MapPath(dir + filename);
                    if (System.IO.File.Exists(filePath))
                        return base.File(filePath, "text/csv", filename);
                    else
                        return Content("Couldn't find file");
                }
                catch
                {
                   return Content("Couldn't find file");
                }        
               
        }
        public ActionResult DownloadFile(string id)
        {
            //bool fileNotFound = false;

            
            try
            {
                //var fs = System.IO.File.Open(Server.MapPath("~/Templates/ODMTemplates_" + id));
                string dir = string.Empty;
                string filename = string.Empty;
                string filePath = string.Empty;
                string fileType = string.Empty;
                switch (id)
                {
                    //case "ODMGuide-Excel":
                    //     dir = "~/Templates/";
                    //     //filename = id + ".xlsx";
                    //     filename = "Advanced Formatting Template.xlsx";
                    //     filePath = Server.MapPath(dir + filename);
                    //     fileType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                    //     break;                
                    //case "UserGuide":
                    //     dir = "~/Templates/";
                    //     filename = id + ".pdf";
                    //     fileType = "application/pdf";
                    //     filePath = Server.MapPath(dir + filename);
                    //     break;
                    //case "DataUploadTutorial":
                    //     dir = "~/Templates/";
                    //     filename = id + ".pdf";
                    //     fileType = "application/pdf";
                    //     filePath = Server.MapPath(dir + filename);
                    //     break;
                    //case "ODMGuide-OpenOffice":

HydroServerTools/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<div class="jumbotron">
    Founded in 2001, the Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI) is a 501(c)3 research organization representing more than 130 U.S.
    universities and international water science-related organizations.
    CUAHSI receives support from the National Science Foundation (NSF) to develop infrastructure and services for the advancement of water science in the United States.
</div>

HydroServerTools/Views/Home/ChangeHistory.cshtml
@{
    ViewBag.Title = "ChangeHistory";
}

<h2>Change History</h2>

Version 0.2 
<ul>
    <li>Added Commit button to "New" and "Updated" tab so to split the upload into 2 steps</li>
    <li>Added template page instead of menu items</li>
    <li>Changed data commit: new data is added in bulk if one records fails to be inserted all records will be rejected. Validation in first step should identify all problems.</li>
    <li>Added detailed error reporting for each record for new and updated records.
</li>   
</ul>

 Version 0.3
<ul>
    <li>Various bugfixes</li>
    <li>Changed Seriescatalog update</li>
    <li>Added controlled vocabularies page</li>
</ul>

HydroServerTools/Views/Home/ControlledVocabulalaries.cshtml
@{
    ViewBag.Title = "ControlledVocabulalaries";
}


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Controlled Vocabulalaries</h3>
    </div>
    <div class="panel-body">
        <ul>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=CensorCodeCV&id=501576825" target="_blank">CensorCodeCV</a> Used to populate the CensorCode field of the DataValues table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=CensorCodeCV&id=501576825" target="_blank">CensorCodeCV</a>:Used to populate the CensorCode field of the DataValues table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=DataTypeCV&id=485576768" target="_blank">DataTypeCV:</a>Used to populate the DataType field of the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=GeneralCategoryCV&id=517576882" target="_blank">GeneralCategoryCV:</a>Used to populate the GeneralCategory field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SampleMediumCV&id=533576939" target="_blank">SampleMediumCV:</a>Used to populate the SampleMedium field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SampleTypeCV&id=549576996" target="_blank">SampleTypeCV:</a>Used to populate the SampleType field in the Samples table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SiteTypeCV&id=901578250" target="_blank">SiteTypeCV:</a>Used to populate the SiteType field in the Sites table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SpatialReferences&id=565577053" target="_blank">SpatialReferences:</a>Defines the coordinate systems used in the Sites table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SpeciationCV&id=581577110" target="_blank">SpeciationCV:</a>Used to poputate the Speciation field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=TopicCategoryCV&id=773577794" target="_blank">TopicCategoryCV:</a>Used to populate the TopicCategory field in the ISOMetadata table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=Units&id=789577851" target="_blank">Units:</a>Defines the units used in the Variables and Offset types tables</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=ValueTypeCV&id=805577908" target="_blank">ValueTypeCV:</a>Used to populate the ValueType field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=VariableNameCV&id=821577965" target="_blank">VariableNameCV:</a>Used to populate the VariableName field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=VerticalDatumCV&id=837578022" target="_blank">VerticalDatumCV:</a>Used to populate the VerticalDatum field im the Sites table</li>
        </ul>
    </div>
</div>

HydroServerTools/Views/Home/ControlledVocabularies.cshtml
@{
    ViewBag.Title = "View ControlledVocabularies";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Controlled Vocabularies</h3>
    </div>
    <div class="panel-body">
        <ul>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=CensorCodeCV&id=773577794" target="_blank">CensorCodeCV</a>:Used to populate the CensorCode field of the DataValues table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=DataTypeCV&id=789577851" target="_blank">DataTypeCV:</a>Used to populate the DataType field of the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=GeneralCategoryCV&id=805577908" target="_blank">GeneralCategoryCV:</a>Used to populate the GeneralCategory field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SampleMediumCV&id=821577965" target="_blank">SampleMediumCV:</a>Used to populate the SampleMedium field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SampleTypeCV&id=837578022" target="_blank">SampleTypeCV:</a>Used to populate the SampleType field in the Samples table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SiteTypeCV&id=853578079" target="_blank">SiteTypeCV:</a>Used to populate the SiteType field in the Sites table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SpatialReferences&id=869578136" target="_blank">SpatialReferences:</a>Defines the coordinate systems used in the Sites table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SpeciationCV&id=885578193" target="_blank">SpeciationCV:</a>Used to poputate the Speciation field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=TopicCategoryCV&id=1109578991" target="_blank">TopicCategoryCV:</a>Used to populate the TopicCategory field in the ISOMetadata table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=Units&id=1125579048" target="_blank">Units:</a>Defines the units used in the Variables and Offset types tables</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=ValueTypeCV&id=1141579105" target="_blank">ValueTypeCV:</a>Used to populate the ValueType field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=VariableNameCV&id=1157579162" target="_blank">VariableNameCV:</a>Used to populate the VariableName field in the Variables table</li>
            <li><a href="http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=VerticalDatumCV&id=1173579219" target="_blank">VerticalDatumCV:</a>Used to populate the VerticalDatum field im the Sites table</li>
        </ul>
    </div>
</div>

HydroServerTools/Views/Home/GoogleForm.cshtml
@{
    Layout = null;
}


<img src="~/Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top" />
<div class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header "></div>
    </div>
</div>



@Html.Action("_GoogleFormIframe", "Home")

HydroServerTools/Views/Home/Index.cshtml
@model HydroserverToolsBusinessObjects.Models.DatabaseTableValueCountModel
@{
    ViewBag.Title = "Home Page";

    ViewBag.Message = TempData["message"];
    ViewBag.UpdateDateTime = TempData["UpdateDateTime"];
    ViewBag.SynchronizedDateTime = TempData["SynchronizedDateTime"];
    ViewBag.LastHarvested = TempData["LastHarvested"];
    ViewBag.NetworkId = TempData["NetworkId"];
    ViewBag.ConnectionName = TempData["ConnectionName"];
    ViewBag.NetworkApiKey = TempData["NetworkApiKey"];

    Layout = "~/Views/Shared/_LayoutBasic.cshtml";

    }

<div class="_container">


    <div class="col-lg-8 ">

        <div class="well">

            @*<h3>Please select: </h3>*@

            @*<button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#setConnection">Set Database Connection</button>*@
            @*<p><a href="/CSVUpload/Sites" class="btn btn-primary btn-lg active" role="button">Import Data into Hydroserver</a></p>*@
         @*   @Html.ActionLink("Import CSV Data into Hydroserver", "UploadData", "CSVUpload", new { id = "Sites" }, new { @class = "btn btn-primary btn active" })*@

            <div class="row">
                <div class="col-sm-5 " style="padding:2px">
                    <p>
                        @Html.ActionLink("Standard Upload", "RevisedUploadData", "CSVUpload", new { id = "SelectUploadType" }, new { @class = "btn btn-primary center-block" })
                    </p>
                    <h5>Upload Sites, Variables, Methods, Sources, Quality Control Levels and Data Values</h5>
                    
                    <h4 style="padding-top:10px"><span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Formatting Template", "DownloadFile", "Export", new { id = "Standard_Formatting_Template" }, new { target = "_blank" })
                    </h4>
                    <h4>
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Formatting Guide", "DownloadFile", "Export", new { id = "Standard_Formatting_Guide" }, new { target = "_blank" })
                    </h4>
                    <h4>
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Uploading Guide", "DownloadFile", "Export", new { id = "Standard_Uploading_Guide" }, new { target = "_blank" })
                    </h4>
                </div>
                <div class="col-sm-5 col-sm-offset-1" style="padding:5px">
                    <p> 
                        @Html.ActionLink("Advanced Upload", "UploadData", "CSVUpload", new { id = "Sites" }, new { @class = "btn btn-primary center-block" })
                    </p>
                    <h5>
                        Upload Sites, Variables, Methods, Sources, Quality Control Levels, Data Values and additional optional metadata tables 
                    </h5>
                    
                    <h4 style="padding-top:10px">
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Formatting Template", "DownloadFile", "Export", new { id = "Advanced_Formatting_Template" }, new { target = "_blank" })
                    </h4>
                    <h4>
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Formatting Guide", "DownloadFile", "Export", new { id = "Advanced_Formatting_Guide" }, new { target = "_blank" })
                    </h4>
                    <h4>
                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                        @Html.ActionLink("Uploading Guide", "DownloadFile", "Export", new { id = "Advanced_Uploading_Guide" }, new { target = "_blank" })
                    </h4>
                </div>
            </div>

            <h3></h3>
            @*<h3>you can allways start with the basic upload and add more comples metadata later.</h3>*@

        </div>

        <br />
        <br />
        @if (User.IsInRole("Admin"))
        {
        <div class="well">
            <h4>
                Synchronize your Data <u>after</u> new data is saved to the database.
            </h4>
            @Html.ActionLink("Synchronize Data", "SynchronizeData", "Home", new { @class = "btn btn-info active " })
            <h5>
                 This step may take several minutes to complete so we recommend that you synchronize at the end of your uploading session.
            </h5>
        </div>

            <div class="well">
                <h4>Set mode to insert. this removes index for unique datavalues.</h4>
                @Html.ActionLink("Set Insert mode", "RemoveDatavalueIndex", "Home", new { @class = "btn btn-info active" })

            </div>
        }
        @if (User.IsInRole("Admin"))
        {
            <div class="well">
                <h4>Remove duplicates</h4>
                @Html.ActionLink("Set Insert mode", "DeleteDuplicatesDatavalues", "Home", new { @class = "btn btn-info active" })

            </div>
        }

    </div>

    @Html.Partial("_CountInTables")





</div>
   
<script src="~/Scripts/custom/jsHelper.js"></script>

HydroServerTools/Views/Home/JQupload.cshtml
@{
    ViewBag.Title = "JQupload";
  ViewBag.Name = "Sites";
}
<script src="~/Scripts/bootstrap.file-input.js"></script>
@*<script src="~/Scripts/jquery.jqupload.min.js"></script>*@
<script src="~/Scripts/custom/Upload.js"></script>


<h2>JQupload</h2>
<div id="demo_message"></div>
<form id="my_form" name="my_form" method="post" action="/CSVUpload/Import2" enctype="multipart/form-data">
    <input type="hidden" name="viewname" value=@ViewBag.Name />
    <input type="file" name="file" title="Search for a file to add">
    <button id="btnUploadAll" class="btn btn-success pull-left" type="submit">
        Upload All
    </button>
</form>

HydroServerTools/Views/Home/Templates.cshtml
@{
    ViewBag.Title = "Templates";
    
}

<div class="panel panel-default">
    <div class="panel-heading">
      
        <h2 class="panel-title">Templates</h2>
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-md-6">
                Please click to download the templates in CSV Format
                <ul class="">
                    <li>@Html.ActionLink("Sites", "DownloadTemplate", "Export", new { id = "Sites" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Variables", "DownloadTemplate", "Export", new { id = "Variables" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("OffsetTypes ", "DownloadTemplate", "Export", new { id = "OffsetTypes" }, new { target = "_blank" })</li>
                    @* <li>@Html.ActionLink("Import ISOMetadata", "ViewTableData", "ViewData", new { identifier = "ISOMetadata" }, null)</li>*@
                    <li>@Html.ActionLink("Sources", "DownloadTemplate", "Export", new { id = "Sources" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Methods", "DownloadTemplate", "Export", new { id = "Methods" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("LabMethods", "DownloadTemplate", "Export", new { id = "LabMethods" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Samples", "DownloadTemplate", "Export", new { id = "Samples" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Qualifiers", "DownloadTemplate", "Export", new { id = "Qualifiers" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("QualityControlLevels", "DownloadTemplate", "Export", new { id = "QualityControlLevels" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("DataValues", "DownloadTemplate", "Export", new { id = "DataValues" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("GroupDescriptions", "DownloadTemplate", "Export", new { id = "GroupDescriptions" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Groups", "DownloadTemplate", "Export", new { id = "Groups" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("DerivedFrom", "DownloadTemplate", "Export", new { id = "DerivedFrom" }, new { target = "_blank" })</li>
                    <li>@Html.ActionLink("Categories", "DownloadTemplate", "Export", new { id = "Categories" }, new { target = "_blank" })</li>

                </ul>
            </div>
            <div class="col-md-6">               
                <br />
                Please click to download User Guide in PDF Format
                <ul class="">
                    <li>@Html.ActionLink("UserGuide", "DownloadFile", "Export", new { id = "UserGuide" }, new { target = "_blank" })</li>
                </ul>
                <br />
                Please click to download User Data Upload Tutorial in PDF Format
                <ul class="">
                    <li>@Html.ActionLink("Data Upload Tutorial", "DownloadFile", "Export", new { id = "DataUploadTutorial" }, new { target = "_blank" })</li>
                </ul>
                <br />
                Please click to download ODM Guide in Excel (xlsx) Format
                <ul class="">
                    <li>@Html.ActionLink("ODMGuide", "DownloadFile", "Export", new { id = "ODMGuide-Excel" }, new { target = "_blank" })</li>
                </ul>
                <br />
                Please click to download ODM Guide in Open Office Format
                <ul class="">
                    <li>@Html.ActionLink("ODMGuide", "DownloadFile", "Export", new { id = "ODMGuide-OpenOffice" }, new { target = "_blank" })</li>
                </ul>
            </div>
        </div>
        </div>
    </div>

HydroServerTools/Views/Home/jquploaddemo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en" xml:lang="en">
<head>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.jqupload.min.js"></script>

    <script type="text/javascript">
        function myfunc(return_message) {
            eval("data=" + return_message);
            $("#demo_message").html(data.message);
        }

        $(document).ready(function () {
            //the simple way, use default alert message and callback
            //$("#my_form").jqupload();

            //the second way, use json object and set the message to a div/span
            //$("#my_form").jqupload({"output":"demo_message"});

            //advanced way, define your own logic to handle the return message
            $("#my_form").jqupload({ "callback": "myfunc" });
            $("#my_form").jqupload_form();
        });
    </script>

</head>
<body>
    <div id="demo_message"></div>
    <form id="my_form" name="my_form" method="post" action="/CSVUpload/Import2" enctype="multipart/form-data">
        <input type="file" name="file" id="file" title="Please select file." />
        <input type="submit" />
    </form>
</body>
</html>