HydroServerTools/Controllers/ViewDataController.cs
using HydroServerTools.Models;
using HydroserverToolsBusinessObjects;
using HydroserverToolsBusinessObjects.Models;
using HydroServerToolsRepository.Repository;
using jQuery.DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ODM_1_1_1EFModel;

using HydroServerToolsEFDerivedObjects;

namespace HydroServerTools.Controllers
{
    [Authorize]
    public class ViewDataController : Controller
    {
        //
        // GET: /View/
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Sites()
        {
            return View("Sites");
        }
        //"Sites", "Variables", "OffsetTypes", "ISOMetadata", "Sources", "Methods", "LabMethods", "Samples", "Qualifiers", "QualityControlLevels", "DataValues", "GroupDescriptions", "Groups", "DerivedFrom", "Categories"};

        //public ActionResult ViewSites()
        //{

        //    string connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name.ToString());
            
        //    var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);
                        
        //    var sitesRepository = new SitesRepository();

        //    return View(sitesRepository.GetAll(entityConnectionString));
          
        //}
        //public ActionResult ViewVariables()
        //{
            
        //    string connectionName = Utils.GetConnectionNameByUserEmail(HttpContext.User.Identity.Name.ToString());
           
        //    var entityConnectionString = Utils.GetDBConnectionStringByName(connectionName);

        //    var variablesRepository = new VariablesRepository();

        //    return View(variablesRepository.GetAll(entityConnectionString));
            
        //}

        [HttpPost]
        public JsonResult Search(JQueryDataTablesModel jQueryDataTablesModel, string identifier)
        {
            int totalRecordCount;
            int searchRecordCount;

            //Get Connection string
            var entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(HttpContext.User.Identity.Name);
            //var entityConnectionString = HydroServerToolsUtils.GetDBEntityConnectionStringByName(connectionName);

            if (String.IsNullOrEmpty(entityConnectionString))
            {
                ModelState.AddModelError(String.Empty, Resources.HYDROSERVER_USERLOOKUP_FAILED);

            }


            var sitesRepository = new SitesRepository();
            var items = sitesRepository.GetSites(entityConnectionString, startIndex: jQueryDataTablesModel.iDisplayStart,
                pageSize: jQueryDataTablesModel.iDisplayLength, sortedColumns: jQueryDataTablesModel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: jQueryDataTablesModel.sSearch);

            var result = from c in items
                         select new[] { 
                    c.SiteCode,
                    c.SiteName,  
                    c.Latitude,  
                    c.Longitude,  
                    c.LatLongDatumSRSName,  
                    c.Elevation_m,  
                    c.VerticalDatum,  
                    c.LocalX,  
                    c.LocalY,  
                    c.LocalProjectionSRSName,  
                    c.PosAccuracy_m,  
                    c.State,  
                    c.County,  
                    c.Comments,  
                    c.SiteType
                };

            return this.DataTablesJson(items: result,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: jQueryDataTablesModel.sEcho);
        }

        [HttpPost]
        public JsonResult VariablesSearch(JQueryDataTablesModel jQueryDataTablesModel, string identifier)
        {
            int totalRecordCount;
            int searchRecordCount;

            //Get Connection string
            var entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(HttpContext.User.Identity.Name);
            //var entityConnectionString = HydroServerToolsUtils.GetDBEntityConnectionStringByName(connectionName);

            if (String.IsNullOrEmpty(entityConnectionString))
            {
                ModelState.AddModelError(String.Empty, Resources.HYDROSERVER_USERLOOKUP_FAILED);

            }


            var repository = new VariablesRepository();
            var items = repository.GetVariables(entityConnectionString, startIndex: jQueryDataTablesModel.iDisplayStart,
                pageSize: jQueryDataTablesModel.iDisplayLength, sortedColumns: jQueryDataTablesModel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: jQueryDataTablesModel.sSearch);

            var result = from c in items
                         select new[] { 
                            //c.VariableID,
                            c.VariableCode,
                            c.VariableName,
                            c.Speciation,
                            c.VariableUnitsName,
                            c.SampleMedium,
                            c.ValueType,
                            c.IsRegular,
                            c.TimeSupport,
                            c.TimeUnitsName,
                            c.DataType,
                            c.GeneralCategory,
                            c.NoDataValue
                };

            return this.DataTablesJson(items: result,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: jQueryDataTablesModel.sEcho);
        }

        [HttpPost]
        public JsonResult OffsetTypesSearch(JQueryDataTablesModel jQueryDataTablesModel, string identifier)
        {
            int totalRecordCount;
            int searchRecordCount;

            //Get Connection string
            var entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(HttpContext.User.Identity.Name);
           // var entityConnectionString = HydroServerToolsUtils.GetDBEntityConnectionStringByName(connectionName);

            if (String.IsNullOrEmpty(entityConnectionString))
            {
                ModelState.AddModelError(String.Empty, Resources.HYDROSERVER_USERLOOKUP_FAILED);

            }


            var repository = new OffsetTypesRepository();
            var items = repository.GetOffsetTypes(entityConnectionString, startIndex: jQueryDataTablesModel.iDisplayStart,
                pageSize: jQueryDataTablesModel.iDisplayLength, sortedColumns: jQueryDataTablesModel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: jQueryDataTablesModel.sSearch);

            var result = from c in items
                         select new[] { 
                            //c.OffsetTypeID,
                            c.OffsetTypeCode,
                            c.OffsetUnitsName,
                            c.OffsetDescription
                };

            return this.DataTablesJson(items: result,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: jQueryDataTablesModel.sEcho);
        }

        [HttpPost]
        public JsonResult SourcesSearch(JQueryDataTablesModel jQueryDataTablesModel, string identifier)
        {
            int totalRecordCount;
            int searchRecordCount;

            //Get Connection string
            var entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(HttpContext.User.Identity.Name);
            //var entityConnectionString = HydroServerToolsUtils.GetDBEntityConnectionStringByName(connectionName);

            if (String.IsNullOrEmpty(entityConnectionString))
            {
                ModelState.AddModelError(String.Empty, Resources.HYDROSERVER_USERLOOKUP_FAILED);

            }


            var repository = new SourcesRepository();
            var items = repository.GetSources(entityConnectionString, startIndex: jQueryDataTablesModel.iDisplayStart,
                pageSize: jQueryDataTablesModel.iDisplayLength, sortedColumns: jQueryDataTablesModel.GetSortedColumns(),
                totalRecordCount: out totalRecordCount, searchRecordCount: out searchRecordCount, searchString: jQueryDataTablesModel.sSearch);

            var result = from c in items
                         select new[] { 
                            c.SourceCode,
                            c.Organization,
                            c.SourceDescription,
                            c.SourceLink,
                            c.ContactName,
                            c.Phone,
                            c.Email,
                            c.Address,
                            c.City,
                            c.State,
                            c.ZipCode,
                            c.Citation,
                            c.TopicCategory,
                            c.Title,
                            c.Abstract,
                            c.ProfileVersion,
                            c.MetadataLink
                };

            return this.DataTablesJson(items: result,
                totalRecords: totalRecordCount,
                totalDisplayRecords: searchRecordCount,
                sEcho: jQueryDataTablesModel.sEcho);
        }

        [HttpPost]
        public JsonResult SamplesSearch(JQueryDataTablesModel jQueryDataTablesModel, string identifier)
        {
            int totalRecordCount;
            int searchRecordCount;

            //Get Connection string
            var entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(HttpContext.User.Identity.Name);

HydroServerTools/Views/Shared/NoDBForm.cshtml
@{
//Layout = null;
}

<div class="container">
    <div class="row">
        <div class="col-lg-6 ">

            <div class="well">
                <h3> @ViewBag.Message;</h3>

                <h4><a href="mailto:help@cuahsi.org">help@cuahsi.org</a></h4>
            </div>
        </div>
    </div>
</div>

HydroServerTools/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HydroServerTools</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    
    @RenderSection("styles", required: false)
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/purl.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
   

</head>
<body>
    <div class="container">
        <div class="row">
            <img src="~/Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top" />
        </div>

        <div class="navbar navbar-inverse">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse ">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav  navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Manage", "Manage", "Home", new { area = "" }, null)</li>
                        <li>@*@Html.ActionLink("Templates", "Templates", "Home", new { area = "" }, null)*@</li>
                        <li>@Html.ActionLink("Controlled Vocabularies", "ControlledVocabularies", "Home", new { area = "" }, null)</li>

                        @*<li>@Html.ActionLink("MVCUploder", "Demo", "Home")</li>
                            <li>@Html.ActionLink("JQupload", "JQupload", "Home", new { identifier = "Sites" }, null)</li>
                            <li>@Html.ActionLink("JQuploaddemo", "JQuploaddemo", "Home", new { identifier = "Sites" }, null)</li>
                            <li>@Html.ActionLink("SimpleUpload", "SimpleUpload", "Home")</li>*@
                        @*<li>@Html.ActionLink("JQueryApI", "JQueryApI", "Home", new { identifier = "Sites" }, null)</li>

                            <li>@Html.ActionLink("Datatable1", "Datatable1", "Home")</li>
                            <li>@Html.ActionLink("Datatable2", "Datatable2", "Home", new { identifier = "Sites" }, null)</li>*@
                        <li class="dropdown hide">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Import CSV Data<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Import Sites", "UploadData", "CSVUpload", new { area = "", id = "Sites" }, null)</li>
                                <li>@Html.ActionLink("Import Variables", "UploadData", "CSVUpload", new { area = "", id = "Variables" }, null)</li>
                                <li>@Html.ActionLink("Import OffsetTypes", "UploadData", "CSVUpload", new { area = "", id = "OffsetTypes" }, null)</li>
                                @*<li>@Html.ActionLink("Import ISOMetadata", "ViewTableData", "ViewData", new { identifier = "ISOMetadata" }, null)</li>*@
                                <li>@Html.ActionLink("Import Sources", "UploadData", "CSVUpload", new { area = "", id = "Sources" }, null)</li>
                                <li>@Html.ActionLink("Import Methods", "UploadData", "CSVUpload", new { area = "", id = "Methods" }, null)</li>
                                <li>@Html.ActionLink("Import LabMethods", "UploadData", "CSVUpload", new { area = "", id = "LabMethods" }, null)</li>
                                <li>@Html.ActionLink("Import Samples", "UploadData", "CSVUpload", new { area = "", id = "Samples" }, null)</li>
                                <li>@Html.ActionLink("Import Qualifiers", "UploadData", "CSVUpload", new { area = "", id = "Qualifiers" }, null)</li>
                                <li>@Html.ActionLink("Import QualityControlLevels", "UploadData", "CSVUpload", new { area = "", id = "QualityControlLevels" }, null)</li>
                                <li>@Html.ActionLink("Import DataValues", "UploadData", "CSVUpload", new { area = "", id = "DataValues" }, null)</li>
                                <li>@Html.ActionLink("Import GroupDescriptions", "UploadData", "CSVUpload", new { area = "", id = "GroupDescriptions" }, null)</li>
                                <li>@Html.ActionLink("Import Groups", "UploadData", "CSVUpload", new { area = "", id = "Groups" }, null)</li>
                                <li>@Html.ActionLink("Import DerivedFrom", "UploadData", "CSVUpload", new { area = "", id = "DerivedFrom" }, null)</li>
                                <li>@Html.ActionLink("Import Categories", "UploadData", "CSVUpload", new { area = "", id = "Categories" }, null)</li>

                            </ul>
                        </li>

                        <li class="dropdown ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Data<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("View Sites", "ViewTableData", "ViewData", new { area = "", identifier = "Sites" }, null)</li>
                                <li>@Html.ActionLink("View Variables", "ViewTableData", "ViewData", new { area = "", identifier = "Variables" }, null)</li>
                                <li>@Html.ActionLink("View OffsetTypes", "ViewTableData", "ViewData", new { area = "", identifier = "OffsetTypes" }, null)</li>
                                @* <li>@Html.ActionLink("View ISOMetadata", "ViewTableData", "ViewData", new { identifier = "ISOMetadata" }, null)</li>*@
                                <li>@Html.ActionLink("View Sources", "ViewTableData", "ViewData", new { area = "", identifier = "Sources" }, null)</li>
                                <li>@Html.ActionLink("View Methods", "ViewTableData", "ViewData", new { area = "", identifier = "Methods" }, null)</li>
                                <li>@Html.ActionLink("View LabMethods", "ViewTableData", "ViewData", new { area = "", identifier = "LabMethods" }, null)</li>
                                <li>@Html.ActionLink("View Samples", "ViewTableData", "ViewData", new { area = "", identifier = "Samples" }, null)</li>
                                <li>@Html.ActionLink("View Qualifiers", "ViewTableData", "ViewData", new { area = "", identifier = "Qualifiers" }, null)</li>
                                <li>@Html.ActionLink("View QualityControlLevels", "ViewTableData", "ViewData", new { area = "", identifier = "QualityControlLevels" }, null)</li>
                                <li>@Html.ActionLink("View DataValues", "ViewTableData", "ViewData", new { area = "", identifier = "DataValues" }, null)</li>
                                <li>@Html.ActionLink("View GroupDescriptions", "ViewTableData", "ViewData", new { area = "", identifier = "GroupDescriptions" }, null)</li>
                                <li>@Html.ActionLink("View Groups", "ViewTableData", "ViewData", new { area = "", identifier = "Groups" }, null)</li>
                                <li>@Html.ActionLink("View DerivedFrom", "ViewTableData", "ViewData", new { area = "", identifier = "DerivedFrom" }, null)</li>
                                <li>@Html.ActionLink("View Categories", "ViewTableData", "ViewData", new { area = "", identifier = "Categories" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("View SeriesCatalog", "ViewTableData", "ViewData", new { area = "", identifier = "SeriesCatalog" }, null)</li>

                            </ul>
                        </li>
                        @if (User.IsInRole("Admin") || User.Identity.Name.ToLower() == "cuahsi.wdc@gmail.com")
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Roles", "Index", "Roles", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Add Connection", "Index", "ConnectionParameters", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Link Connections", "Index", "ConnectionParametersUsers", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Manage Accounts", "Index", "ServiceRegistrations", new { area = "" }, null)</li>                                    
                                    <li>@Html.ActionLink("Register as a new user", "Register", "Account", new { area = "" }, null)</li>
                                </ul>
                            </li>
                        }
                    </ul>
                }
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.Partial("_LoginPartial")</li>
                    <li>@Html.ActionLink("Sign Out", "SignOut", "Account", new { @class = "btn btn-secondary", @id = "logout" }, null)</li>
                </ul>
            </div>
        </div>

        @RenderBody()

        <footer>
            <hr />
            <p><a href="https://github.com/CUAHSI/Azure-Hydroservertools/issues" class="h5" target="_blank">Report a bug here!</a><span style="float:right"> &copy; @DateTime.Now.Year CUAHSI - Version 2.0.8</span></p>
      </footer>
    </div>  
   @* @Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@

  
    @RenderSection("scripts", required: false)
  
</body>
</html> 

HydroServerTools/Views/Shared/_LayoutBasic.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HydroServerTools</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

    @RenderSection("styles", required: false)
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/purl.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
    @*<script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
        <script src="/signalr/hubs"></script>
        <script>

        $(function() {
            // Save the reference to the SignalR hub
            var theHub = $.connection.yourAppHub;

            // Invoke the function to be called back from the server
            // when changes are detected

            // Start the SignalR client-side listener
            $.connection.hub.start().done(function () {
                // Do here any initialization work you may need

            });
        });
        </script>*@

</head>
<body>
    <div class="container">
        <div class="row">
            <img src="~/Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top" />
        </div>

        <div class="navbar navbar-inverse">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse ">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav  navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Manage", "Manage", "Home", new { area = "" }, null)</li>
                        @*  <li>@Html.ActionLink("Templates", "Templates", "Home", new { area = "" }, null)</li>*@
                        <li>@Html.ActionLink("Controlled Vocabularies", "ControlledVocabularies", "Home", new { area = "" }, null)</li>

                        @*<li>@Html.ActionLink("MVCUploder", "Demo", "Home")</li>
                            <li>@Html.ActionLink("JQupload", "JQupload", "Home", new { identifier = "Sites" }, null)</li>
                            <li>@Html.ActionLink("JQuploaddemo", "JQuploaddemo", "Home", new { identifier = "Sites" }, null)</li>
                            <li>@Html.ActionLink("SimpleUpload", "SimpleUpload", "Home")</li>*@
                        @*<li>@Html.ActionLink("JQueryApI", "JQueryApI", "Home", new { identifier = "Sites" }, null)</li>

                            <li>@Html.ActionLink("Datatable1", "Datatable1", "Home")</li>
                            <li>@Html.ActionLink("Datatable2", "Datatable2", "Home", new { identifier = "Sites" }, null)</li>*@


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Data<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("View Sites", "ViewTableData", "ViewData", new { area = "", identifier = "Sites" }, null)</li>
                                <li>@Html.ActionLink("View Variables", "ViewTableData", "ViewData", new { area = "", identifier = "Variables" }, null)</li>
                                <li>@Html.ActionLink("View Sources", "ViewTableData", "ViewData", new { area = "", identifier = "Sources" }, null)</li>
                                <li>@Html.ActionLink("View Methods", "ViewTableData", "ViewData", new { area = "", identifier = "Methods" }, null)</li>
                                <li>@Html.ActionLink("View DataValues", "ViewTableData", "ViewData", new { area = "", identifier = "DataValues" }, null)</li>
                                <li>@Html.ActionLink("View SeriesCatalog", "ViewTableData", "ViewData", new { area = "", identifier = "SeriesCatalog" }, null)</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("View OffsetTypes", "ViewTableData", "ViewData", new { area = "", identifier = "OffsetTypes" }, null)</li>
                                 @*<li>@Html.ActionLink("View ISOMetadata", "ViewTableData", "ViewData", new { identifier = "ISOMetadata" }, null)</li>*@
                                <li>@Html.ActionLink("View LabMethods", "ViewTableData", "ViewData", new { area = "", identifier = "LabMethods" }, null)</li>
                                <li>@Html.ActionLink("View Samples", "ViewTableData", "ViewData", new { area = "", identifier = "Samples" }, null)</li>
                                <li>@Html.ActionLink("View Qualifiers", "ViewTableData", "ViewData", new { area = "", identifier = "Qualifiers" }, null)</li>
                                <li>@Html.ActionLink("View QualityControlLevels", "ViewTableData", "ViewData", new { area = "", identifier = "QualityControlLevels" }, null)</li>
                                <li>@Html.ActionLink("View GroupDescriptions", "ViewTableData", "ViewData", new { area = "", identifier = "GroupDescriptions" }, null)</li>
                                <li>@Html.ActionLink("View Groups", "ViewTableData", "ViewData", new { area = "", identifier = "Groups" }, null)</li>
                                <li>@Html.ActionLink("View DerivedFrom", "ViewTableData", "ViewData", new { area = "", identifier = "DerivedFrom" }, null)</li>
                                <li>@Html.ActionLink("View Categories", "ViewTableData", "ViewData", new { area = "", identifier = "Categories" }, null)</li>


                            </ul>
                        </li>
                        @if (User.IsInRole("Admin") || User.Identity.Name == "mseul@cuahsi.org")
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Roles", "Index", "Roles", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Add Connection", "Index", "ConnectionParameters", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Link Connections", "Index", "ConnectionParametersUsers", new { area = "Admin" }, null)</li>
                                    <li>@Html.ActionLink("Manage Accounts", "Index", "ServiceRegistrations", new { area = "" }, null)</li>
                                    <li>@Html.ActionLink("Register as a new user", "Register", "Account", new { area = "" }, null)</li>
                                </ul>
                            </li>
                        }
                    </ul>
                }
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.Partial("_LoginPartial")</li>
                    <li>@Html.ActionLink("Sign Out", "SignOut", "Account", new { @class = "btn btn-secondary", @id = "logout" }, null)</li>
                </ul>
            </div>
        </div>




        @RenderBody()


        <footer>
            <hr />
            <p><a href="https://github.com/CUAHSI/Azure-Hydroservertools/issues" class="h5" target="_blank">Report a bug here!</a><span style="float:right"> &copy; @DateTime.Now.Year CUAHSI - Version 2.0.8</span></p>
        </footer>
    </div>
    @* @Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@


    @RenderSection("scripts", required: false)

</body>
</html>

HydroServerTools/Views/Shared/_LayoutBulkUpload.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HydroServerTools</title>

    <!-- Cannot be interpreted by RazonEngine ??? -->
    @*@Styles.Render("~/Content/css")*@
    <link rel="stylesheet" type="text/css" href="@(ViewBag.urlBase)Content/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="@(ViewBag.urlBase)Content/Site.css" />

    @RenderSection("styles", required: false)
    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/jquery-ui-1.10.3.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="~/Scripts/purl.js"></script>
        <script src="~/Scripts/bootbox.min.js"></script>*@
    <script src="@(ViewBag.urlBase)Scripts/jquery-1.10.2.min.js"></script>
    <script src="@(ViewBag.urlBase)Scripts/jquery-ui-1.10.3.min.js"></script>
    <script src="@(ViewBag.urlBase)Scripts/bootstrap.min.js"></script>
    <script src="@(ViewBag.urlBase)Scripts/purl.js"></script>
    <script src="@(ViewBag.urlBase)Scripts/bootbox.min.js"></script>

</head>
<body>
    <div class="container">
        <div class="row">
            @*<img src="~/Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top" />*@
            <img src="@(ViewBag.urlBase)Images/Hydroserver/HydroserverLogo.png" class="center img-thumbnail" style="border:0px; vertical-align:top" />
            
        </div>

        @RenderBody()

        <footer>
            <hr />
            <p><a href="https://github.com/CUAHSI/Azure-Hydroservertools/issues" class="h5" target="_blank">Report a bug here!</a><span style="float:right"> &copy; @DateTime.Now.Year CUAHSI - Version 2.0.1</span></p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>