HydroServerTools/Controllers/CSVUploadController.cs
using CsvHelper;

using HydroServerTools.Models;
using HydroserverToolsBusinessObjects;
using HydroserverToolsBusinessObjects.Models;
using HydroServerToolsRepository.Repository;
using ICSharpCode.SharpZipLib.Core;
using ICSharpCode.SharpZipLib.Zip;
using jQuery.DataTables.Mvc;
using Microsoft.ApplicationServer.Caching;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

using System.Threading.Tasks;

namespace HydroServerTools.Controllers
{
    [Authorize]
    public class CSVUploadController : Controller
    {
        public const string CacheName = "default";

        public string identifier = System.Web.HttpContext.Current.User.Identity.Name;
        //
        // GET: /CSVUpload/
        public ActionResult Index(ExternalLoginConfirmationViewModel model)
        {

            return View();
        }
    
        //public ActionResult UploadData()
        //{
        //    return View("UploadData");
        //}

        [HttpGet]
        public ActionResult Sites()
        {
            var model = new SiteModel();
            return View("Sites", model);
        }
        [HttpGet]
        public ActionResult Variables()
        {
            var model = new VariablesModel();
            return View("Variables", model);
        }
        [HttpGet]
        public ActionResult OffsetTypes()
        {
            var model = new OffsetTypesModel();
            return View("OffsetTypes", model);
        }
        [HttpGet]
        public ActionResult ISOMetadata()
        {
            return View("ISOMetadata");
        }
        [HttpGet]
        public ActionResult Sources()
        {
            var model = new SourcesModel();
            return View("Sources", model);
        }
        [HttpGet]
        public ActionResult Methods()
        {
            var model = new MethodModel();
            return View("Methods", model);
        }
        [HttpGet]
        public ActionResult LabMethods()
        {
            var model = new LabMethodModel();
            return View("LabMethods", model);
        }
        [HttpGet]
        public ActionResult Samples()
        {
            var model = new SampleModel();
            return View("Samples", model);
        }
        [HttpGet]
        public ActionResult Qualifiers()
        {
            var model = new QualifiersModel();
            return View("Qualifiers", model);
        }
        [HttpGet]
        public ActionResult QualityControlLevels()
        {
            var model = new QualityControlLevelModel();
            return View("QualityControlLevels", model);
        }
        [HttpGet]
        public ActionResult DataValues()
        {
            var model = new DataValuesModel();
            return View("DataValues", model);
        }
        [HttpGet]
        public ActionResult GroupDescriptions()
        {
            var model = new GroupDescriptionModel();
            return View("GroupDescriptions", model);
        }
        [HttpGet]
        public ActionResult Groups()
        {
            var model = new GroupsModel();
            return View("Groups", model);
        }
        [HttpGet]
        public ActionResult DerivedFrom()
        {
            var model = new DerivedFromModel();
            return View("DerivedFrom", model);
        }
        [HttpGet]
        public ActionResult Categories()
        {
            var model = new CategoriesModel();
            return View("Categories", model);
        }
        [HttpGet]

        public ActionResult UploadData(string id)
        {
            ViewBag.name = id;
            return View();
        }

        //A simple method to retrieve db table counts for the current user...
        private DatabaseTableValueCountModel getTableValueCounts()
        {
            DatabaseTableValueCountModel tableValueCounts = null;

            //Get connection name for current user...
            var userName = HttpContext.User.Identity.Name.ToString();
            string connectionName = HydroServerToolsUtils.GetConnectionName(userName);
            if (connectionName != Resources.NOT_LINKED_TO_DATABASE)
            {
                //Get connection string for current user...
                string entityConnectionString = HydroServerToolsUtils.BuildConnectionStringForUserName(userName);
                if (!String.IsNullOrEmpty(entityConnectionString))
                {
                    //Create repository instance, retrieve table value counts...
                    var databaseRepository = new DatabaseRepository();
                    tableValueCounts = databaseRepository.GetDatabaseTableValueCount(entityConnectionString);
                }

                //Retrieve service status...
                try
                {
                    var networkidString = HydroServerToolsUtils.GetNetworkIdForUserName(userName);
                    int networkId = -1;
                    bool res = int.TryParse(networkidString, out networkId);
                    if (res == true)
                    {
                        HISNetwork hisNetwork = HydroServerToolsUtils.getHISNetworksDataForServiceName(networkId);
                        TempData["LastHarvested"] = hisNetwork.LastHarvested;
                        //BCC - 26-Apr-2018 - Field issue - 500 error returned by SelectUploadType when NetworkID is numeric...
                        TempData["NetworkId"] = hisNetwork.NetworkID.ToString();
                    }

                }
                catch (Exception)
                {
                    //For now - take no action...
                }

                //Retrieve update stats...
                if (!String.IsNullOrEmpty(entityConnectionString))
                {
                    var userId = HydroServerToolsUtils.GetUserIdFromUserName(userName);
                    var db = new ApplicationDbContext();
                    var trackUpdates = new TrackUpdates();
                    var p = (from c in db.TrackUpdates
                             where c.UserId == userId
                             select new
                             {
                                 c.IsUpdated,
                                 c.UpdateDateTime,
                                 c.IsSynchronized,
                                 c.SynchronizedDateTime

                             }).FirstOrDefault();
                    if (p != null)
                    {
                        TimeZoneInfo estZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");

                        TempData["UpdateDateTime"] = TimeZoneInfo.ConvertTimeFromUtc(p.UpdateDateTime, estZone).ToString("MM/dd/yy H:mm:ss zzz");
                        if (p.IsSynchronized == true)
                            TempData["SynchronizedDateTime"] = TimeZoneInfo.ConvertTimeFromUtc(p.SynchronizedDateTime, estZone).ToString("MM/dd/yy H:mm:ss zzz");
                        else
                        {
                            TempData["SynchronizedDateTime"] = "Scheduled";
                        }
                    }
                }
            }

            //Processing complete - return result
            return tableValueCounts;
        }

        public ActionResult RevisedUploadData(string id)
        {
            if (!String.IsNullOrEmpty(id))
            {
                var viewName = String.Empty;
                DatabaseTableValueCountModel tableValueCounts = null;
                TempData["UpdateDateTime"] = "unknown";
                TempData["SynchronizedDateTime"] = "unknown";
                TempData["LastHarvested"] = "unknown";
                TempData["NetworkId"] = "unknown";

                string idLower = id.ToLowerInvariant();
                string idQualifier = String.Empty;

                switch (idLower)
                {
                    case "dbsummaryreport":
                        {
                            viewName = "DbSummaryReport";
                            break;
                        }
                    //case "draganddropfiles":                //Reverse button input...
                    case "draganddropfiles_meta_data":      //Select Upload Type input...
                    case "draganddropfiles_data_values":    //Select Upload Type input...
                        {
                            //viewName = "DragAndDropFiles";
                            viewName = "DragAndDropFilesRevised";
                            //Set temp data for qualifier, if indicated
                            switch (idLower)
                            {
                                case "draganddropfiles_meta_data":
                                    TempData["qualifier"] = "meta_data";
                                    break;
                                case "draganddropfiles_data_values":
                                    TempData["qualifier"] = "data_values";
                                    break;
                                default: //("draganddropfiles")
                                    //Take no action - use current 'qualifier' value...
                                    break;
                            }
                            break;
                        }
                    case "selectuploadtype":
                        {
                            viewName = "SelectUploadType";
                            tableValueCounts = getTableValueCounts();
                            //Re-set temp data for qualifier...
                            break;
                        }
                    case "validatefiles":
                        {
                            viewName = "ValidateFiles";

HydroServerTools/Views/CSVUpload/DataValues.cshtml
@model HydroserverToolsBusinessObjects.Models.DataValuesModel

@{
    ViewBag.Title = "DataValues";
    ViewBag.Name = "datavalues";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}
@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table_jui.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
    
}
@Html.Action("_Breadcrumb", "CSVUpload", new { id = ViewBag.Name })

<div class="container" id="tabs">

    @{Html.RenderPartial("_UploadTabs");}
    
    <div id="tabs-0">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 0 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-1">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 1 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-2">

        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 2 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-3">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 3 }, { "viewName", ViewBag.Name } });}
    </div>

    <div class="well-sm alert-info hide" id="loading">
        <div id="monitor">
            Committing records...
            @*<img src="~/Images/ajax-loader.gif" />*@
        </div>

        @*<p>
            <label for="file">Choose file</label>
            <input type="file" id="file" name="file" accept="image/jpg, image/jpeg, image/gif, image/png" />
        </p>
        <p><button id="upload">Upload</button></p>
        <p><span id="progress" class="progress">0%</span></p>*@

    </div>
</div>


@*@Html.Action("_Pager", "CSVUpload", new { name = ViewBag.Name })*@


@section scripts
{
    <script>
        $(document).ready(function () {
            initCommitAndCancelButton('@ViewBag.Name');
            oTable = $('#0').dataTable(getDatatableOptions('@ViewBag.Name', 0));
            toggleCommitButtons(oTable,0);
        });
    </script>

    @*    <script type='text/javascript' src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>*@
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/custom/CSVUploadHelper.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>
}

HydroServerTools/Views/CSVUpload/DerivedFrom.cshtml
@model HydroserverToolsBusinessObjects.Models.DerivedFromModel

@{
    ViewBag.Title = "DerivedFrom";
    ViewBag.Name = "derivedfrom";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}
@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table_jui.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { id = ViewBag.Name })

<div class="container" id="tabs">

    @{Html.RenderPartial("_UploadTabs");}

    <div id="tabs-0">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 0 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-1">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 1 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-2">

        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 2 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-3">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 3 }, { "viewName", ViewBag.Name } });}
    </div>
</div>


@*@Html.Action("_Pager", "CSVUpload", new { name = ViewBag.Name })*@


@section scripts
{
    <script>
        $(document).ready(function () {
            initCommitAndCancelButton('@ViewBag.Name');
            oTable = $('#0').dataTable(getDatatableOptions('@ViewBag.Name', 0));
            toggleCommitButtons(oTable,0);

        });
    </script>

    @*  <script type='text/javascript' src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>*@
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/custom/CSVUploadHelper.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
}

HydroServerTools/Views/CSVUpload/GroupDescriptions.cshtml
@model HydroserverToolsBusinessObjects.Models.GroupDescriptionModel

@{
    ViewBag.Title = "GroupDescriptions";
    ViewBag.Name = "groupdescriptions";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}
@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table_jui.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { id = ViewBag.Name })

<div class="container" id="tabs">

    @{Html.RenderPartial("_UploadTabs");}

    <div id="tabs-0">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 0 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-1">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 1 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-2">

        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 2 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-3">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 3 }, { "viewName", ViewBag.Name } });}
    </div>
</div>


@*@Html.Action("_Pager", "CSVUpload", new { name = ViewBag.Name })*@


@section scripts
{
    <script>
        $(document).ready(function () {
           initCommitAndCancelButton('@ViewBag.Name');
            oTable = $('#0').dataTable(getDatatableOptions('@ViewBag.Name', 0));
            toggleCommitButtons(oTable,0);

        });
    </script>

    @*  <script type='text/javascript' src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>*@
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/custom/CSVUploadHelper.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
}

HydroServerTools/Views/CSVUpload/Groups.cshtml
@model HydroserverToolsBusinessObjects.Models.GroupsModel

@{
    ViewBag.Title = "Groups";
    ViewBag.Name = "groups";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}
@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/demo_table_jui.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/themes/base/minified/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { id = ViewBag.Name })

<div class="container" id="tabs">

    @{Html.RenderPartial("_UploadTabs");}

    <div id="tabs-0">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 0 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-1">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 1 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-2">

        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 2 }, { "viewName", ViewBag.Name } });}
    </div>
    <div id="tabs-3">
        @{ Html.RenderPartial("_UploadDataBaseTable", Model, new ViewDataDictionary { { "index", 3 }, { "viewName", ViewBag.Name } });}
    </div>
</div>


@*@Html.Action("_Pager", "CSVUpload", new { name = ViewBag.Name })*@


@section scripts
{
    <script>
        $(document).ready(function () {
           initCommitAndCancelButton('@ViewBag.Name');
            oTable = $('#0').dataTable(getDatatableOptions('@ViewBag.Name', 0));
            toggleCommitButtons(oTable,0);

        });
    </script>

    @*  <script type='text/javascript' src="http://datatables.net/release-datatables/media/js/jquery.dataTables.js"></script>*@
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/custom/CSVUploadHelper.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
}

HydroServerTools/Views/CSVUpload/ISOMetadata.cshtml
@model IEnumerable<HydroserverToolsBusinessObjects.Models.ISOMetadataModel>
@{
    ViewBag.Title = "ISOMetadata";
    ViewBag.Name = "ISOMetadata";
    Layout = "~/Views/Shared/_LayoutBasic.cshtml";
}


@section styles
{
    <link href="~/Content/DataTables-1.9.4/media/css/demo_page.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/media/css/jquery.dataTables_themeroller.css" rel="stylesheet" />
    <link href="~/Content/DataTables-1.9.4/extras/TableTools/media/css/TableTools_JUI.css" rel="stylesheet" />
    <link href="~/Content/ViewData.css" rel="stylesheet" />
}
@Html.Action("_Breadcrumb", "CSVUpload", new { name = ViewBag.Name })
@if (Model == null)
{
    Html.RenderPartial("_UploadForm");
}
@if (Model != null)
{
    <div class="panel panel-info">
        <span class="red">You successfully added @ViewBag.numberOfCorrectRecords new record(s) to the @ViewBag.Name table. @ViewBag.numberOfDuplicateRecords record(s) were duplicates.</span>
    </div>
    if (Model.Count() > 0)
    {
        <div class="display" id="DBTable">
            <h4>List of rejected  @ViewBag.Name please review and re-upload</h4>
            @{Html.RenderPartial("_DataBaseTable", Model);}
        </div>
    }
}
@section scripts
{
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/extras/TableTools/media/js/TableTools.min.js"></script>
    <script src="~/Scripts/custom/ViewDataHelper.js"></script>
<script src="~/Scripts/bootbox.min.js"></script>
}

HydroServerTools/Views/CSVUpload/Index.cshtml
@model HydroServerTools.Models.ConnectionModel
@{
    ViewBag.Title = "VerticalTab";
}
@section styles{
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

    <link href="~/Content/DataTables-1.9.4/media/css/demo_table.css" rel="stylesheet" />

}
<h1>Please set up connection</h1>
<div>

    @using (Html.BeginForm("TestConnection", "CSVUpload", new { @class = "form-horizontal" }))
    {

        <div class="control-group">
            @Html.LabelFor(m => m.ServerName, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.ServerName, new { @value = "mseul-cuahsi" })
                @Html.ValidationMessageFor(m => m.ServerName, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.DataSourceName, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.DataSourceName, new { @value = "LittleBear_1_1_1" })
                @Html.ValidationMessageFor(m => m.DataSourceName, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Username, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(m => m.Username, new { @value = "martin" })
                @Html.ValidationMessageFor(m => m.Username, null, new { @class = "help-inline" })
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.Password, new { @class = "control-label" })
            <div class="controls">
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password, null, new { @class = "help-inline" })
            </div>
        </div>

        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Test Connection</button>
            <a href="/CSVUpload/Upload" class="btn btn-default active" role="button">Link</a>

        </div>



        @*@Html.ValidationSummary(true)
            <div class="row">
                <fieldset>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.ServerName);

                    </div>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.ServerName, new { @Value = "mseul-cuahsi", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ServerName)


                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.DataSourceName);
                    </div> <div class="editor-field">
                        @Html.TextBoxFor(model => model.DataSourceName, new { @Value = "LittleBear_1_1_1", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DataSourceName)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Username);
                    </div><div class="editor-field">
                        @Html.TextBoxFor(model => model.Username, new { @Value = "martin", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Username)
                    </div>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Password)
                    </div><div class="editor-field">
                        @Html.EditorFor(model => model.Password, new { @Value = "ms", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Password)
                    </div>


                </fieldset>
            </div>
                 <div class="row">
                    <input type="submit" class="btn btn-primary" value="connect" />
                </div>
        *@
        if (@Model != null)
        {

            if (@Model.Status != null)
            {
                if (Model.Message.ToString().Length > 0)
                {
                    if (@Model.Status.ToLower() == "success")
                    {

                        <p><div class="alert alert-success">@Model.Message;</div></p>

                    }
                    else
                    {
                        <p><div class="alert alert-danger">@Model.Message;</div></p>
                    }

                }
            }

        }
        @*if (@Model.Message != null)
            {
                @Model.Message;
            }*@
    }

</div>


@section scripts{
    <script src="~/Scripts/jquery-ui-1.10.3.js"></script>
    <script src="~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/UploadHelper.js"></script>
    <script src="~/Scripts/bootbox.min.js"></script>

}

HydroServerTools/Views/CSVUpload/RejectedItems.cshtml
@{
    ViewBag.Title = "RejectedItems";
}

<h2>RejectedItems</h2>

@section styles {
    @Styles.Render("~/Content/css/DataTablesEditorCombo")    
}



@section Scripts {
    @Scripts.Render("~/bundles/js/DataTablesEditorCombo")
}